# Generated by Django 2.0.4 on 2018-04-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20180419_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='apps/basket/photos/player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='apps/basket/photos/logo'),
        ),
    ]
