# Generated by Django 2.0.4 on 2018-04-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20180419_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='birth_date',
            new_name='birthh_date',
        ),
    ]
